'use client'

import { isPremium, getRidesForExport } from '@/lib/storage'
import { DaySummary } from '@/lib/types'
import { formatCurrency, calculateProfit } from '@/lib/calculate'
import { useTranslation, formatDate, localeConfig, Locale } from '@/lib/i18n'

interface Props {
  summaries: DaySummary[]
}

export default function ExportButton({ summaries }: Props) {
  const { t, locale } = useTranslation()
  const premium = isPremium()
  const hasData = summaries.length > 0

  const handleExport = () => {
    if (!premium) {
      window.open('https://pay.hotmart.com/Q105978279A', '_blank')
      return
    }
    generatePDF(summaries, locale)
  }

  const handleCSV = () => {
    if (!premium) {
      window.open('https://pay.hotmart.com/Q105978279A', '_blank')
      return
    }
    const rides = getRidesForExport()
    if (rides.length === 0) return

    const headers = [
      t('export.csv_data'), t('export.csv_amount'),
      t('export.csv_fuel'), t('export.csv_profit'),
      t('export.csv_cost_km'), t('export.csv_status'),
    ]
    const rows = rides.map(r => [
      new Date(r.date).toLocaleDateString(localeConfig[locale].locale),
      formatCurrency(r.amount, locale),
      formatCurrency(r.fuelCost, locale),
      formatCurrency(r.profit, locale),
      formatCurrency(r.costPerKm, locale),
      r.status === 'profit' ? t('export.status_profit') : r.status === 'loss' ? t('export.status_loss') : t('export.status_zero'),
    ])

    const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n')
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${t('export.csv_title')}-${new Date().toISOString().split('T')[0]}.csv`
    a.click()
    URL.revokeObjectURL(url)
  }

  if (!hasData) return null

  return (
    <div className="flex items-center gap-2">
      <button
        onClick={handleCSV}
        className="px-3 py-2 text-xs font-semibold text-brand-600 dark:text-brand-400 border border-brand-200 dark:border-brand-800 rounded-lg hover:bg-brand-50 dark:hover:bg-brand-900/50 transition-all flex items-center justify-center gap-1.5"
      >
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
        </svg>
        {premium ? t('export.csv') : '🔒 CSV'}
      </button>
      <button
        onClick={handleExport}
        className="px-4 py-2 text-xs font-semibold bg-gradient-to-r from-brand-600 to-brand-500 text-white rounded-lg hover:from-brand-700 hover:to-brand-600 transition-all flex items-center justify-center gap-1.5"
      >
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
        {premium ? t('export.exportar') : t('export.desbloquear')}
      </button>
    </div>
  )
}

function generatePDF(summaries: DaySummary[], locale: Locale) {
  const t = (key: string, vars?: Record<string, string | number>) => {
    const dict: Record<string, Record<string, string>> = {
      pt: {
        'export.relatorio': 'Relatório LucroReal',
        'export.periodo': 'Período: {days} dia(s) — Gerado em {date}',
        'export.data': 'Data', 'export.corridas': 'Corridas',
        'export.faturamento': 'Faturamento', 'export.combustivel': 'Combustível',
        'export.km': 'KM', 'export.lucro': 'Lucro',
        'export.lucro_total': 'Lucro Total', 'export.km_rodados': 'KM Rodados',
        'export.dias': 'Dias', 'export.rodape': 'Relatório gerado por LucroReal — lucroreal.app',
      },
      es: {
        'export.relatorio': 'Informe LucroReal',
        'export.periodo': 'Período: {days} día(s) — Generado el {date}',
        'export.data': 'Fecha', 'export.corridas': 'Carreras',
        'export.faturamento': 'Facturación', 'export.combustivel': 'Combustible',
        'export.km': 'KM', 'export.lucro': 'Ganancia',
        'export.lucro_total': 'Ganancia Total', 'export.km_rodados': 'KM Recorridos',
        'export.dias': 'Días', 'export.rodape': 'Informe generado por LucroReal — lucroreal.app',
      },
      en: {
        'export.relatorio': 'LucroReal Report',
        'export.periodo': 'Period: {days} day(s) — Generated on {date}',
        'export.data': 'Date', 'export.corridas': 'Rides',
        'export.faturamento': 'Revenue', 'export.combustivel': 'Fuel',
        'export.km': 'KM', 'export.lucro': 'Profit',
        'export.lucro_total': 'Total Profit', 'export.km_rodados': 'KM Driven',
        'export.dias': 'Days', 'export.rodape': 'Report generated by LucroReal — lucroreal.app',
      },
    }
    const text = dict[locale]?.[key]
    if (!text) return key
    if (!vars) return text
    return text.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? `{${k}}`))
  }

  const totalProfit = summaries.reduce((s, d) => s + d.totalProfit, 0)
  const totalKm = summaries.reduce((s, d) => s + d.totalKm, 0)
  const totalRides = summaries.reduce((s, d) => s + d.totalRides, 0)
  const totalAmount = summaries.reduce((s, d) => s + d.totalAmount, 0)
  const totalFuel = summaries.reduce((s, d) => s + d.totalFuelCost, 0)
  const days = summaries.length
  const cfg = localeConfig[locale]

  const printWindow = window.open('', '_blank')
  if (!printWindow) return

  const dateLocale = cfg.locale

  const rows = summaries.map(d => `
    <tr>
      <td style="padding:8px;border:1px solid #ddd">${new Date(d.date).toLocaleDateString(dateLocale)}</td>
      <td style="padding:8px;border:1px solid #ddd;text-align:center">${d.totalRides}</td>
      <td style="padding:8px;border:1px solid #ddd;text-align:right">${formatCurrency(d.totalAmount, locale)}</td>
      <td style="padding:8px;border:1px solid #ddd;text-align:right">${formatCurrency(d.totalFuelCost, locale)}</td>
      <td style="padding:8px;border:1px solid #ddd;text-align:right">${d.totalKm.toFixed(1)} km</td>
      <td style="padding:8px;border:1px solid #ddd;text-align:right;color:${d.totalProfit >= 0 ? '#10B981' : '#EF4444'};font-weight:bold">${formatCurrency(d.totalProfit, locale)}</td>
    </tr>
  `).join('')

  printWindow.document.write(`
    <html>
    <head>
      <title>${t('export.relatorio')}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
        h1 { color: #059669; font-size: 24px; margin-bottom: 4px; }
        .sub { color: #888; font-size: 14px; margin-bottom: 24px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
        th { background: #059669; color: white; padding: 10px 8px; text-align: left; font-size: 13px; }
        tr:nth-child(even) { background: #f9f9f9; }
        .resumo { display: flex; gap: 16px; flex-wrap: wrap; margin-bottom: 24px; }
        .card { background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 12px 20px; flex: 1; min-width: 120px; }
        .card label { font-size: 11px; color: #888; display: block; }
        .card value { font-size: 18px; font-weight: bold; color: #059669; }
        @media print { body { padding: 20px; } }
      </style>
    </head>
    <body>
      <h1>${t('export.relatorio')}</h1>
      <div class="sub">${t('export.periodo', { days, date: new Date().toLocaleDateString(dateLocale) })}</div>

      <div class="resumo">
        <div class="card"><label>${t('export.corridas')}</label><value>${totalRides}</value></div>
        <div class="card"><label>${t('export.lucro_total')}</label><value>${formatCurrency(totalProfit, locale)}</value></div>
        <div class="card"><label>${t('export.faturamento')}</label><value>${formatCurrency(totalAmount, locale)}</value></div>
        <div class="card"><label>${t('export.km_rodados')}</label><value>${totalKm.toFixed(1)} km</value></div>
        <div class="card"><label>${t('export.combustivel')}</label><value>${formatCurrency(totalFuel, locale)}</value></div>
        <div class="card"><label>${t('export.dias')}</label><value>${days}</value></div>
      </div>

      <table>
        <thead>
          <tr>
            <th>${t('export.data')}</th>
            <th>${t('export.corridas')}</th>
            <th>${t('export.faturamento')}</th>
            <th>${t('export.combustivel')}</th>
            <th>${t('export.km')}</th>
            <th>${t('export.lucro')}</th>
          </tr>
        </thead>
        <tbody>
          ${rows}
        </tbody>
      </table>

      <div style="text-align:center;color:#aaa;font-size:12px;margin-top:32px">
        ${t('export.rodape')}
      </div>

      <script>
        window.onload = function() { window.print() }
      <\/script>
    </body>
    </html>
  `)
  printWindow.document.close()
}
